# Experiment

## Import libraries

In [36]:
import pandas as pd

In [37]:
file_path = "vietstock_2000_2025.csv"

In [38]:
df = pd.read_csv(file_path)
df

,Chỉ tiêu,Đơn vị tính,Quý 1/2005,Quý 2/2005,6 tháng/2005,Quý 3/2005,9 tháng/2005,Quý 4/2005,Quý 1/2006,Quý 2/2006,...,9 tháng/2023,Quý 4/2023,Quý 1/2024,Quý 2/2024,6 tháng/2024,Quý 3/2024,9 tháng/2024,Quý 4/2024,Quý 1/2025,Đồ thị
0,Nông nghiệp,%,15.69,NaN,22.11,NaN,20.6,NaN,14.4,NaN,...,11.51,12.38,11.77,11.3,11.55,11.72,11.64,12.59,11.56,NaN
1,Công nghiệp,%,43.03,NaN,39.79,NaN,41.3,NaN,43.2,NaN,...,37.16,37.46,35.73,37.04,36.44,38.67,37.1,37.76,36.31,NaN
2,Dịch vụ,%,41.28,NaN,38.1,NaN,38.1,NaN,42.4,NaN,...,42.72,42.35,43.48,43.34,43.35,41.58,42.8,42.04,43.44,NaN
3,Tổng GDP,%,7.2,NaN,7.63,NaN,8.1,NaN,7.2,NaN,...,4.24,6.72,5.66,6.93,6.42,7.43,6.82,7.55,6.93,NaN
4,Nông nghiệp,%,4.1,NaN,4.23,NaN,4.1,NaN,2.1,NaN,...,3.43,4.13,2.98,3.34,3.38,2.95,3.2,2.99,3.74,NaN
5,Công nghiệp,%,8.5,NaN,9.5,NaN,10,NaN,8.7,NaN,...,2.41,7.35,6.28,8.29,7.51,8.98,8.19,8.35,7.42,NaN
6,Dịch vụ,%,7,NaN,7.6,NaN,8.2,NaN,7.4,NaN,...,6.32,7.29,6.12,7.06,6.64,7.52,6.95,8.21,7.7,NaN
7,GDP theo giá cố định (2010),Tỷ VNĐ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"4,176,814","1,643,902","1,396,660","1,508,387","2,907,904","1,567,923","4,472,215","1,773,652","1,502,807",NaN
8,Nông nghiệp,Tỷ VNĐ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"439,759","184,545","145,600","151,303","297,533","161,767","460,392","192,991","153,001",NaN
9,Công nghiệp,Tỷ VNĐ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"1,509,766","605,975","488,208","545,237","1,035,164","588,545","1,623,915","657,896","526,666",NaN
10,Dịch vụ,Tỷ VNĐ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"1,840,018","716,362","627,420","677,030","1,304,919","680,490","1,980,801","776,143","681,303",NaN
11,GDP theo giá hiện hành,Tỷ VNĐ,"164,243","216,026","380,269","206,829","587,098","250,760","184,359","242,186",...,"7,268,043","2,921,187","2,513,091","2,727,565","5,245,201","2,894,998","8,099,698","3,297,408","2,809,099",NaN
12,Nông nghiệp,Tỷ VNĐ,"25,768","58,301","84,069","37,018","121,087","53,961","26,563","61,776",...,"836,618","361,551","295,777","308,208","606,019","339,433","942,663","415,226","324,685",NaN
13,Công nghiệp,Tỷ VNĐ,"70,679","80,655","151,334","90,915","242,249","101,558","79,569","93,300",...,"2,700,557","1,094,325","897,978","1,010,232","1,911,511","1,119,474","3,005,083","1,245,248","1,020,031",NaN
14,Dịch vụ,Tỷ VNĐ,"67,796","77,070","144,866","78,896","223,762","95,241","78,227","87,110",...,"3,104,755","1,237,147","1,092,719","1,182,165","2,273,774","1,203,831","3,466,550","1,386,287","1,220,270",NaN

In [39]:
filtered_col_df = df[
    [col for col in df.columns if not col.startswith(("Quý 2", "Quý 3", "Quý 4"))]
]
filtered_col_df

,Chỉ tiêu,Đơn vị tính,Quý 1/2005,6 tháng/2005,9 tháng/2005,Quý 1/2006,6 tháng/2006,9 tháng/2006,Quý 1/2007,6 tháng/2007,...,6 tháng/2022,9 tháng/2022,Quý 1/2023,6 tháng/2023,9 tháng/2023,Quý 1/2024,6 tháng/2024,9 tháng/2024,Quý 1/2025,Đồ thị
0,Nông nghiệp,%,15.69,22.11,20.6,14.4,20.71,20.08,14.2,20.7,...,11.05,11.27,11.66,11.32,11.51,11.77,11.55,11.64,11.56,NaN
1,Công nghiệp,%,43.03,39.79,41.3,43.2,40.53,41.5,43.3,40.5,...,39.3,38.69,35.47,36.62,37.16,35.73,36.44,37.1,36.31,NaN
2,Dịch vụ,%,41.28,38.1,38.1,42.4,38.76,38.42,42.5,38.8,...,40.63,41.31,43.65,43.25,42.72,43.48,43.35,42.8,43.44,NaN
3,Tổng GDP,%,7.2,7.63,8.1,7.2,7.4,7.84,7.7,7.87,...,6.42,8.83,3.32,3.72,4.24,5.66,6.42,6.82,6.93,NaN
4,Nông nghiệp,%,4.1,4.23,4.1,2.1,3,3.32,2.3,2.67,...,2.78,2.99,2.52,3.07,3.43,2.98,3.38,3.2,3.74,NaN
5,Công nghiệp,%,8.5,9.5,10,8.7,9.3,9.85,9.3,9.88,...,7.7,9.44,-0.4,1.13,2.41,6.28,7.51,8.19,7.42,NaN
6,Dịch vụ,%,7,7.6,8.2,7.4,7.7,8.03,7.8,8.41,...,6.6,10.57,6.79,6.33,6.32,6.12,6.64,6.95,7.7,NaN
7,GDP theo giá cố định (2010),Tỷ VNĐ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,602,382","4,006,189","1,320,755","2,727,672","4,176,814","1,396,660","2,907,904","4,472,215","1,502,807",NaN
8,Nông nghiệp,Tỷ VNĐ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"272,241","424,501","140,836","284,870","439,759","145,600","297,533","460,392","153,001",NaN
9,Công nghiệp,Tỷ VNĐ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"984,355","1,477,553","459,243","971,854","1,509,766","488,208","1,035,164","1,623,915","526,666",NaN
10,Dịch vụ,Tỷ VNĐ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"1,094,980","1,728,262","590,817","1,212,811","1,840,018","627,420","1,304,919","1,980,801","681,303",NaN
11,GDP theo giá hiện hành,Tỷ VNĐ,"164,243","380,269","587,098","184,359","426,545","674,835","210,878","493,455",...,"4,429,425","6,839,048","2,300,882","4,741,481","7,268,043","2,513,091","5,245,201","8,099,698","2,809,099",NaN
12,Nông nghiệp,Tỷ VNĐ,"25,768","84,069","121,087","26,563","88,339","135,501","30,042","102,071",...,"489,649","770,891","268,224","536,480","836,618","295,777","606,019","942,663","324,685",NaN
13,Công nghiệp,Tỷ VNĐ,"70,679","151,334","242,249","79,569","172,869","280,081","91,276","200,091",...,"1,740,713","2,646,169","816,185","1,736,335","2,700,557","897,978","1,911,511","3,005,083","1,020,031",NaN
14,Dịch vụ,Tỷ VNĐ,"67,796","144,866","223,762","78,227","165,337","259,253","89,560","191,293",...,"1,799,520","2,825,023","1,004,341","2,050,730","3,104,755","1,092,719","2,273,774","3,466,550","1,220,270",NaN

In [40]:
rotated_df = filtered_col_df.transpose()
rotated_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
Chỉ tiêu,Nông nghiệp,Công nghiệp,Dịch vụ,Tổng GDP,Nông nghiệp,Công nghiệp,Dịch vụ,GDP theo giá cố định (2010),Nông nghiệp,Công nghiệp,Dịch vụ,GDP theo giá hiện hành,Nông nghiệp,Công nghiệp,Dịch vụ
Đơn vị tính,%,%,%,%,%,%,%,Tỷ VNĐ,Tỷ VNĐ,Tỷ VNĐ,Tỷ VNĐ,Tỷ VNĐ,Tỷ VNĐ,Tỷ VNĐ,Tỷ VNĐ
Quý 1/2005,15.69,43.03,41.28,7.2,4.1,8.5,7,NaN,NaN,NaN,NaN,"164,243","25,768","70,679","67,796"
6 tháng/2005,22.11,39.79,38.1,7.63,4.23,9.5,7.6,NaN,NaN,NaN,NaN,"380,269","84,069","151,334","144,866"
9 tháng/2005,20.6,41.3,38.1,8.1,4.1,10,8.2,NaN,NaN,NaN,NaN,"587,098","121,087","242,249","223,762"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Quý 1/2024,11.77,35.73,43.48,5.66,2.98,6.28,6.12,"1,396,660","145,600","488,208","627,420","2,513,091","295,777","897,978","1,092,719"
6 tháng/2024,11.55,36.44,43.35,6.42,3.38,7.51,6.64,"2,907,904","297,533","1,035,164","1,304,919","5,245,201","606,019","1,911,511","2,273,774"
9 tháng/2024,11.64,37.1,42.8,6.82,3.2,8.19,6.95,"4,472,215","460,392","1,623,915","1,980,801","8,099,698","942,663","3,005,083","3,466,550"
Quý 1/2025,11.56,36.31,43.44,6.93,3.74,7.42,7.7,"1,502,807","153,001","526,666","681,303","2,809,099","324,685","1,020,031","1,220,270"
Đồ thị,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
clean_col_rotated_df = rotated_df.iloc[2:, :7]
clean_col_rotated_df

                  0      1      2     3     4     5     6
Quý 1/2005    15.69  43.03  41.28   7.2   4.1   8.5     7
6 tháng/2005  22.11  39.79   38.1  7.63  4.23   9.5   7.6
9 tháng/2005   20.6   41.3   38.1   8.1   4.1    10   8.2
Quý 1/2006     14.4   43.2   42.4   7.2   2.1   8.7   7.4
6 tháng/2006  20.71  40.53  38.76   7.4     3   9.3   7.7
...             ...    ...    ...   ...   ...   ...   ...
Quý 1/2024    11.77  35.73  43.48  5.66  2.98  6.28  6.12
6 tháng/2024  11.55  36.44  43.35  6.42  3.38  7.51  6.64
9 tháng/2024  11.64   37.1   42.8  6.82   3.2  8.19  6.95
Quý 1/2025    11.56  36.31  43.44  6.93  3.74  7.42   7.7
Đồ thị          NaN    NaN    NaN   NaN   NaN   NaN   NaN

[62 rows x 7 columns]

In [42]:
new_columns = clean_col_rotated_df.columns.to_list()
new_columns[0] = "agriculture_share"
new_columns[1] = "industry_share"
new_columns[2] = "service_share"
new_columns[3] = "gdp_true_growth_acc"
new_columns[4] = "agriculture_true_growth_acc"
new_columns[5] = "industry_true_growth_acc"
new_columns[6] = "service_true_growth_acc"
clean_col_rotated_df.columns = new_columns
clean_col_rotated_df

,agriculture_share,industry_share,service_share,gdp_true_growth_acc,agriculture_true_growth_acc,industry_true_growth_acc,service_true_growth_acc
Quý 1/2005,15.69,43.03,41.28,7.2,4.1,8.5,7
6 tháng/2005,22.11,39.79,38.1,7.63,4.23,9.5,7.6
9 tháng/2005,20.6,41.3,38.1,8.1,4.1,10,8.2
Quý 1/2006,14.4,43.2,42.4,7.2,2.1,8.7,7.4
6 tháng/2006,20.71,40.53,38.76,7.4,3,9.3,7.7
...,...,...,...,...,...,...,...
Quý 1/2024,11.77,35.73,43.48,5.66,2.98,6.28,6.12
6 tháng/2024,11.55,36.44,43.35,6.42,3.38,7.51,6.64
9 tháng/2024,11.64,37.1,42.8,6.82,3.2,8.19,6.95
Quý 1/2025,11.56,36.31,43.44,6.93,3.74,7.42,7.7
Đồ thị,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
clean_col_rotated_df = clean_col_rotated_df.reset_index()
clean_col_rotated_df = clean_col_rotated_df.rename(columns={"index": "period"})

In [44]:
df = clean_col_rotated_df[clean_col_rotated_df["period"] != "Đồ thị"].copy()

In [45]:
clean_col_rotated_df

,period,agriculture_share,industry_share,service_share,gdp_true_growth_acc,agriculture_true_growth_acc,industry_true_growth_acc,service_true_growth_acc
0,Quý 1/2005,15.69,43.03,41.28,7.2,4.1,8.5,7
1,6 tháng/2005,22.11,39.79,38.1,7.63,4.23,9.5,7.6
2,9 tháng/2005,20.6,41.3,38.1,8.1,4.1,10,8.2
3,Quý 1/2006,14.4,43.2,42.4,7.2,2.1,8.7,7.4
4,6 tháng/2006,20.71,40.53,38.76,7.4,3,9.3,7.7
...,...,...,...,...,...,...,...,...
57,Quý 1/2024,11.77,35.73,43.48,5.66,2.98,6.28,6.12
58,6 tháng/2024,11.55,36.44,43.35,6.42,3.38,7.51,6.64
59,9 tháng/2024,11.64,37.1,42.8,6.82,3.2,8.19,6.95
60,Quý 1/2025,11.56,36.31,43.44,6.93,3.74,7.42,7.7
61,Đồ thị,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
def extract_year_quarter(period):
    import re

    year_match = re.search(r"(\d{4})", period)
    year = int(year_match.group(1)) if year_match else None

    if "Quý 1" in period:
        quarter = 1
    elif "6 tháng" in period:
        quarter = 2
    elif "9 tháng" in period:
        quarter = 3
    else:
        quarter = None

    return pd.Series([year, quarter])

In [47]:
clean_col_rotated_df[["year", "quarter"]] = clean_col_rotated_df["period"].apply(
    extract_year_quarter
)
cols = ["year", "quarter"] + [
    col for col in clean_col_rotated_df.columns if col not in ["year", "quarter"]
]
clean_col_rotated_df = clean_col_rotated_df[cols]

In [48]:
clean_col_rotated_df.drop(columns="period", inplace=True)
clean_col_rotated_df

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8308\1663970300.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_col_rotated_df.drop(columns="period", inplace=True)

,year,quarter,agriculture_share,industry_share,service_share,gdp_true_growth_acc,agriculture_true_growth_acc,industry_true_growth_acc,service_true_growth_acc
0,2005.0,1.0,15.69,43.03,41.28,7.2,4.1,8.5,7
1,2005.0,2.0,22.11,39.79,38.1,7.63,4.23,9.5,7.6
2,2005.0,3.0,20.6,41.3,38.1,8.1,4.1,10,8.2
3,2006.0,1.0,14.4,43.2,42.4,7.2,2.1,8.7,7.4
4,2006.0,2.0,20.71,40.53,38.76,7.4,3,9.3,7.7
...,...,...,...,...,...,...,...,...,...
57,2024.0,1.0,11.77,35.73,43.48,5.66,2.98,6.28,6.12
58,2024.0,2.0,11.55,36.44,43.35,6.42,3.38,7.51,6.64
59,2024.0,3.0,11.64,37.1,42.8,6.82,3.2,8.19,6.95
60,2025.0,1.0,11.56,36.31,43.44,6.93,3.74,7.42,7.7
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df = pd.read_csv(file_path)

df = df[[col for col in df.columns if not col.startswith(("Quý 2", "Quý 3", "Quý 4"))]]

df = df.transpose()

df = df.iloc[2:, :7]

new_columns = df.columns.to_list()
new_columns[0] = "agriculture_share"
new_columns[1] = "industry_share"
new_columns[2] = "service_share"
new_columns[3] = "gdp_true_growth_acc"
new_columns[4] = "agriculture_true_growth_acc"
new_columns[5] = "industry_true_growth_acc"
new_columns[6] = "service_true_growth_acc"
df.columns = new_columns

df = df.reset_index().rename(columns={"index": "period"})

df = df[df["period"] != "Đồ thị"].copy()


def extract_year_quarter(period):
    import re

    year_match = re.search(r"(\d{4})", period)
    year = int(year_match.group(1)) if year_match else None

    if "Quý 1" in period:
        quarter = 1
    elif "6 tháng" in period:
        quarter = 2
    elif "9 tháng" in period:
        quarter = 3
    else:
        quarter = None

    return pd.Series([year, quarter])


df[["year", "quarter"]] = df["period"].apply(extract_year_quarter)

cols = ["year", "quarter"] + [
    col for col in df.columns if col not in ["year", "quarter"]
]

df = df[cols]

df.drop(columns="period", inplace=True)

df

,year,quarter,agriculture_share,industry_share,service_share,gdp_true_growth_acc,agriculture_true_growth_acc,industry_true_growth_acc,service_true_growth_acc
0,2005,1,15.69,43.03,41.28,7.2,4.1,8.5,7
1,2005,2,22.11,39.79,38.1,7.63,4.23,9.5,7.6
2,2005,3,20.6,41.3,38.1,8.1,4.1,10,8.2
3,2006,1,14.4,43.2,42.4,7.2,2.1,8.7,7.4
4,2006,2,20.71,40.53,38.76,7.4,3,9.3,7.7
...,...,...,...,...,...,...,...,...,...
56,2023,3,11.51,37.16,42.72,4.24,3.43,2.41,6.32
57,2024,1,11.77,35.73,43.48,5.66,2.98,6.28,6.12
58,2024,2,11.55,36.44,43.35,6.42,3.38,7.51,6.64
59,2024,3,11.64,37.1,42.8,6.82,3.2,8.19,6.95
60,2025,1,11.56,36.31,43.44,6.93,3.74,7.42,7.7

In [50]:
df[df.columns] = df[df.columns].apply(pd.to_numeric, errors='coerce')
df

,year,quarter,agriculture_share,industry_share,service_share,gdp_true_growth_acc,agriculture_true_growth_acc,industry_true_growth_acc,service_true_growth_acc
0,2005,1,15.69,43.03,41.28,7.20,4.10,8.50,7.00
1,2005,2,22.11,39.79,38.10,7.63,4.23,9.50,7.60
2,2005,3,20.60,41.30,38.10,8.10,4.10,10.00,8.20
3,2006,1,14.40,43.20,42.40,7.20,2.10,8.70,7.40
4,2006,2,20.71,40.53,38.76,7.40,3.00,9.30,7.70
...,...,...,...,...,...,...,...,...,...
56,2023,3,11.51,37.16,42.72,4.24,3.43,2.41,6.32
57,2024,1,11.77,35.73,43.48,5.66,2.98,6.28,6.12
58,2024,2,11.55,36.44,43.35,6.42,3.38,7.51,6.64
59,2024,3,11.64,37.10,42.80,6.82,3.20,8.19,6.95
60,2025,1,11.56,36.31,43.44,6.93,3.74,7.42,7.70

In [51]:
import numpy as np

df.dtypes.tolist()[2] == np.float64

True

In [ ]:
for row in df.iterrows():
    print(row[])

TypeError: tuple indices must be integers or slices, not str