# Feature Selection: Test

## Install libraries

In [1]:
# !pip install -r ../../requirements.txt

## Import libraries

In [2]:
import os
import sys
import pandas as pd

# go one level up from where the notebook is running
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))

from logger.logger import Logger
from feature_selector.feature_selector import FeatureSelector
from utils.constants import *
from utils.enums import *
from dtos.tabular_database_driver_dtos.tabular_database_driver_dtos import *

## Helper functions

In [3]:
def auto_convert(df: pd.DataFrame) -> pd.DataFrame:
    for col in df.columns:
        # Dates
        if "date" in col.lower():
            df[col] = pd.to_datetime(df[col], errors="coerce")

        # Codes
        elif "code" in col.lower():
            df[col] = df[col].astype("string")

        # Market IDs
        elif "market_id" in col.lower():
            df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

        # OHLC
        elif col.lower() in ["open", "high", "low", "close"]:
            df[col] = pd.to_numeric(df[col], errors="coerce").astype(float)

        # Volume
        elif "volume" in col.lower():
            df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

    return df

## Initialize the Logger

In [4]:
my_logger = Logger(file_name=FEATURE_SELECTION_LOG_FILE_TEST)

## Initialize the Feature Selector

In [14]:
my_feature_selector = FeatureSelector(logger=my_logger, feature_selector_type=FeatureSelectorType.XGB_REGRESSOR)

NameError: name 'FeatureSelectorType' is not defined

## Parameters

In [6]:
# stock_code = "FPT"
output_column_name = "y"

## Load data

In [7]:
my_feature_selector.connect_to_database(database_name=os.getenv("BRONZE_POSTGRES_DATABASE"))

In [9]:
df = pd.read_csv("../../src/PJME_hourly_date_features.csv")
df

,PJME_MW,hour,dayofweek,quarter,month,year,dayofyear,dayofmonth,weekofyear
0,26498.0,1,1,4,12,2002,365,31,1
1,25147.0,2,1,4,12,2002,365,31,1
2,24574.0,3,1,4,12,2002,365,31,1
3,24393.0,4,1,4,12,2002,365,31,1
4,24860.0,5,1,4,12,2002,365,31,1
...,...,...,...,...,...,...,...,...,...
145361,44284.0,20,0,1,1,2018,1,1,1
145362,43751.0,21,0,1,1,2018,1,1,1
145363,42402.0,22,0,1,1,2018,1,1,1
145364,40164.0,23,0,1,1,2018,1,1,1
145365,38608.0,0,1,1,1,2018,2,2,1

In [11]:
train = df.loc[df.index < 120_000]
test = df.loc[df.index >= 120_000]

In [12]:
train

,PJME_MW,hour,dayofweek,quarter,month,year,dayofyear,dayofmonth,weekofyear
0,26498.0,1,1,4,12,2002,365,31,1
1,25147.0,2,1,4,12,2002,365,31,1
2,24574.0,3,1,4,12,2002,365,31,1
3,24393.0,4,1,4,12,2002,365,31,1
4,24860.0,5,1,4,12,2002,365,31,1
...,...,...,...,...,...,...,...,...,...
119995,31256.0,20,3,2,4,2015,113,23,17
119996,32298.0,21,3,2,4,2015,113,23,17
119997,31103.0,22,3,2,4,2015,113,23,17
119998,28782.0,23,3,2,4,2015,113,23,17
119999,26652.0,0,4,2,4,2015,114,24,17

In [ ]:
test

,PJME_MW,hour,dayofweek,quarter,month,year,dayofyear,dayofmonth,weekofyear
120000,22333.0,1,2,2,4,2015,112,22,17
120001,21547.0,2,2,2,4,2015,112,22,17
120002,21175.0,3,2,2,4,2015,112,22,17
120003,21118.0,4,2,2,4,2015,112,22,17
120004,21746.0,5,2,2,4,2015,112,22,17
...,...,...,...,...,...,...,...,...,...
145361,44284.0,20,0,1,1,2018,1,1,1
145362,43751.0,21,0,1,1,2018,1,1,1
145363,42402.0,22,0,1,1,2018,1,1,1
145364,40164.0,23,0,1,1,2018,1,1,1
145365,38608.0,0,1,1,1,2018,2,2,1